### ISSUE TITLE
License oversight?

### ISSUE THREAD

**Issue by fpl** [jordan2175/doxygen-filter-perl#1]
Hi Bret, I was preparing a Debian package for this module to be released in next Debian main repository when I found that POD.pm apparently releases that file under GPL-3.0 and some unknown 'commercial' license. Indeed it also cites the LICENSE file (where all stuff seems released under Apache2.0).

> =head1 LICENSE
> Doxygen::Filter::Perl::POD is dual licensed GPLv3 and Commerical. See the LICENSE
> file for more details.
> =cut

Could you please clarify?

**Comment by jordan2175** [comment]
Thanks for catching that.  I have fixed the license notice in the POD.pm file to match the README file.
