### ISSUE TITLE
Version string in new release 1.73 not updated

### ISSUE THREAD

**Issue by jschleus** [jordan2175/doxygen-filter-perl#21]
First many thanks for the new release 1.73.

A small issue: At least in the files
```
 lib/Doxygen/Filter.pm:our $VERSION     = '1.72';
 lib/Doxygen/Filter/Perl/POD.pm:our $VERSION     = '1.72';
 lib/Doxygen/Filter/Perl.pm:our $VERSION     = '1.72';
 Changes:v1.72 - 2015-03-23
```
I found still the old version string.

**Comment by albert-github** [comment]
I've just pushed a proposed patch, pull request #22

**Comment by jordan2175** [comment]
I merged the pull requests, deleted the release of 1.73 and re-released it to Github, Sourceforge, and CPAN.
